### PR TITLE
Added support for Mdx

### PR DESCRIPTION
**Pull request by przemuh**

### CODE REVIEW

**Comment by phcloud** [comment]
Is there any documentation? when using gatsby-plugin-i18n & gatsby-plugin-mdx, where should I configure and which key/value should i configure？

**Comment by przemuh** [comment]
@phcloud There is nothing special here :) 

Just add `gatsby-plugin-i18n` to your `gatsby-config.js` and you are ready to go.

One caveat here...the `gatsby-plugin-i18n` with MDX support has not been released/published to npm yet ;) I think, this is the responsibility of the maintainer :) @angeloocana - I cannot do it (no permissions ;)) The Merge Request has been merged but the current npm version doesn't contain my changes.

So.... If you want to use it, you need to:

- clone this repo `gatsby-plugin-i18n`
- do the `yarn install`
- go to the `packages/gatsby-plugin-i18n`, run `yarn build`
- go to your app/repo and install the plugin from your hard disk `yarn install /path/to/the/cloned/repo/of/the/i18n/plugin`

This is a workaround, and of course, it will not work "in the cloud" ;) We need to wait until @angeloocana will publish the next version on npm.

**Comment by bolonio** [comment]
Hi @angeloocana , could you please publish a new release? The support for mdx was already merged. Thanks :)

**Comment by shreyasminocha** [comment]
Another workaround would be to install using [npm's support for GH repos](https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly) (`npm install angeloocana/gatsby-plugin-i18n`, I believe) until @angeloocana publishes a release.

**Comment by bolonio** [comment]
Unfortunately that's not an option. I got this error message:

> npm ERR! Can't install github:angeloocana/gatsby-plugin-i18n#683c3c3c935629af78673d23ca9d02dbf7216397: Missing package name

**Comment by onichandame** [comment]
The fact that this git repo is a lerna monorepo prevents npm or yarn to install it using git protocol.I am quite curious why the last publish of this package on npm registry was 2 years ago?

**Pull request merged**
